# --- BUILD STAGE ---
FROM node:16.15.1-alpine3.16 AS build-stage

WORKDIR /client

COPY package*.json ./

# Збільшуємо таймаут і кількість спроб для npm
RUN npm config set fetch-timeout 600000
RUN npm config set fetch-retries 5
RUN npm install --include=dev

COPY . .

RUN npm run build

# --- PRODUCTION STAGE ---
FROM nginx:1.13.12-alpine AS production-stage

RUN mkdir -p /var/www/html/

# Копіюємо зібраний фронтенд у Nginx
COPY --from=build-stage /client/build /var/www/html/

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./nginx.vh.default.conf /etc/nginx/nginx.vh.default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
