GET http://localhost:5000/users/id/transactions?limit=10&offset=0 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJidXllcmZuIiwidXNlcklkIjoxLCJyb2xlIjoiY3VzdG9tZXIiLCJsYXN0TmFtZSI6ImJ1eWVybG4iLCJhdmF0YXIiOiJhbm9uLnBuZyIsImRpc3BsYXlOYW1lIjoiYnV5ZXJkbiIsImJhbGFuY2UiOiIwIiwiZW1haWwiOiJidXllckBnbWFpbC5jb20iLCJyYXRpbmciOjAsImlhdCI6MTc1OTQzNDMwOCwiZXhwIjoxNzU5NDM3OTA4fQ.maoj73bld711mmtvoKgWe7L7i54JBNEDEoX-wB7EDb0